export const packageInfo = {
  name: "pi-orc",
  description: "Pi Orchestrator for verified AI development workflows."
} as const;

export { GhGitHubAdapter, startIssueWorkflow, syncPullRequestReview } from "./github/index.js";
export { createBootstrapPlanDryRun, generateBootstrapPlan, renderBootstrapPlanMarkdown } from "./repo-bootstrap/index.js";
export {
  decideWorkflowAction,
  defaultPlanningWorkerProfile,
  defaultNewProjectIntakeOptions,
  defaultVerificationWorkerProfile,
  defaultWorkerProfiles,
  defaultWorkflowPolicies,
  GitHubProjectOwnerTypeSchema,
  NewProjectIntakeSchema,
  PiSdkWorkerRuntime,
  ProjectRepositoryVisibilitySchema,
  WorkerContextPolicySchema,
  WorkerErrorSchema,
  WorkerEventSchema,
  WorkerHandoffSchema,
  WorkerOutputContractSchema,
  WorkerPermissionSetSchema,
  WorkerProfileSchema,
  WorkerRunInputSchema,
  WorkerRunResultSchema,
  WorkerToolPolicySchema,
  workflowActionCategories,
  WorkflowArtifactSchema,
  workflowModes,
  type PiSdkAgentSession,
  type PiSdkSessionFactory,
  type PiSdkSessionFactoryOptions,
  type PiSdkWorkerRuntimeOptions
} from "./runtime/index.js";
export type {
  GitHubProjectOwnerType,
  NewProjectIntake,
  ProjectRepositoryVisibility,
  WorkflowActionCategory,
  WorkerContextPolicy,
  WorkerHandoff,
  WorkerOutputContract,
  WorkerPermissionSet,
  WorkerProfile,
  WorkerRunArtifact,
  WorkerRunError,
  WorkerRunEvent,
  WorkerRunInput,
  WorkerRunResult,
  WorkerToolPolicy,
  WorkflowArtifact,
  WorkflowMode,
  WorkflowPolicy,
  WorkflowPolicyDecision,
  WorkflowPolicyDecisionStatus,
  WorkerRuntime
} from "./runtime/index.js";
export type {
  BootstrapDirectoryAction,
  BootstrapFileAction,
  BootstrapGitAction,
  BootstrapGitHubAction,
  BootstrapPlan,
  BootstrapPlanDryRun,
  BootstrapPolicyGate
} from "./repo-bootstrap/index.js";
export type {
  AddProjectItemAction,
  CreateIssueAction,
  CreateLabelAction,
  CreateProjectAction,
  CreateRepositoryAction,
  GitHubAction,
  GitHubActionResult,
  GitHubAdapter,
  GitHubAuthCheck,
  GitHubCommandOutput,
  GitHubCommandPlan,
  GitHubCommandRunner,
  GitHubExecuteOptions,
  GitHubRepositoryVisibility,
  IssueStartAdapter,
  IssueStartContext,
  IssueStartInput,
  IssueStartIssue,
  IssueStartMutationKind,
  IssueStartMutationPlan,
  IssueStartProject,
  IssueStartProjectItem,
  IssueStartRef,
  IssueStartResult,
  LinkProjectAction,
  PullRequestBotReaction,
  PullRequestCheck,
  PullRequestCheckState,
  PullRequestReaction,
  PullRequestReviewComment,
  PullRequestReviewCommentSource,
  PullRequestReviewCommentVerification,
  PullRequestReviewContext,
  PullRequestReviewContextAdapter,
  PullRequestReviewItem,
  PullRequestReviewMutationPlan,
  PullRequestReviewRef,
  PullRequestReviewSyncInput,
  PullRequestReviewSyncResult,
  PullRequestReviewThread,
  PullRequestReviewVerificationStep
} from "./github/index.js";
